apiVersion: v1
kind: Pod
metadata:
  name: prime-pod 
  labels:
    name: prime-pod
spec:
  containers:
  - name: prime-pod
    image: binjip978/prime-service:0.2.0-dev
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
        name: http
