apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime
spec:
  selector:
    matchLabels:
      app: prime
  replicas: 2
  template:
    metadata:
      labels:
        app: prime
    spec:
      containers:
      - name: prime-pod
        image: binjip978/prime-service:0.2.0-dev-arm32
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 20
          failureThreshold: 3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
          - containerPort: 8080
            protocol: TCP
