apiVersion: v1
kind: Pod
metadata:
  name: prime-pod 
  labels:
    name: prime-pod
spec:
  containers:
  - name: prime-pod
    image: binjip978/prime-service:0.2.0-dev-arm32
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 20
      failureThreshold: 3
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m" 
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
        name: http
