apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:

    scrape_configs:
      - job_name: 'raspberry-cluster'
        scrape_interval: 300s
        static_configs:
          - targets: ['100.103.98.91:9100', '100.93.252.69:9100', '100.87.104.31:9100']
        metric_relabel_configs:
          - source_labels: ['node_thermal_zone_temp', 'node_load1']
            action: keep
