kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "raspberry-ingress"
spec:
  rules:
    - host: pi4a.fleet
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port: 
                  number: 3000
