version: '3'
services:
  database:
    image: "postgres:13"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - data-vol:/var/lib/postgresql/data

volumes:
  data-vol:
