kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "example-ingress"
spec:
  rules:
    - host: pi2a.fleet
      http:
        paths:
          - path: /version
            backend: 
              serviceName: grpc-example-http-server
              servicePort: 8000
          - path: /graph
            backend:
                serviceName: prometheus-service
                servicePort: 9090
          - path: /static
            backend:
                serviceName: prometheus-service
                servicePort: 9090
          - path: /api/v1
            backend:
                serviceName: prometheus-service
                servicePort: 9090
